name: mobile_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:

  cupertino_icons: ^1.0.2
  awesome_snackbar_content: ^0.1.3
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/aa_logo.png
    - assets/luggage_icon.png